#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export NODE_ENV=production

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8080" \
        cd /app/dillinger s6-setuidgid abc node app
