#!/usr/bin/with-contenv bash
# shellcheck shell=bash

i=/app/dillinger/configs
if [[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]]; then
    rm -Rf "$i" && \
    ln -s /config/"$(basename "$i")" "$i"
fi

if [[ -e "$i" && ! -L "$i" ]]; then
    mv "$i" /config/"$(basename "$i")" && \
    ln -s /config/"$(basename "$i")" "$i"
fi

# permissions
lsiown -R abc:abc \
    /config

lsiown -R abc:abc \
    /app/dillinger/public/
